// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BookLibraryContext))]
    partial class BookLibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApplicationCore.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bibliography")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Updated")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bibliography = "Bibliography 1",
                            CountryId = 1,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(4669),
                            CreatedBy = 1,
                            DateOfBirth = new DateTime(1950, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Name",
                            LastName = "Surname",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(4670),
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 2,
                            Bibliography = "Bibliography 2",
                            CountryId = 1,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(4673),
                            CreatedBy = 1,
                            DateOfBirth = new DateTime(1950, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Name 2",
                            LastName = "Surname 2",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(4674),
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 3,
                            Bibliography = "Bibliography 3",
                            CountryId = 1,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(4675),
                            CreatedBy = 1,
                            DateOfBirth = new DateTime(1950, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Name 3",
                            LastName = "Surname 3",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(4675),
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 10,
                            Bibliography = "Bibliography 8",
                            CountryId = 2,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(4676),
                            CreatedBy = 1,
                            DateOfBirth = new DateTime(1975, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Elon",
                            LastName = "Musk",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(4677),
                            UpdatedBy = 1
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<decimal>("ListPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<decimal>("RentalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UnitNumber")
                        .HasColumnType("int");

                    b.Property<int>("UnitsRented")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<int>("YearOfPublish")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5520),
                            CreatedBy = 1,
                            Description = "Description about the book1",
                            LanguageId = 1,
                            ListPrice = 0.70m,
                            PublisherId = 1,
                            RentalPrice = 1.20m,
                            Title = "Book1",
                            UnitNumber = 3,
                            UnitsRented = 10,
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5522),
                            UpdatedBy = 1,
                            YearOfPublish = 1999
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5524),
                            CreatedBy = 1,
                            Description = "Description about the book2",
                            LanguageId = 2,
                            ListPrice = 0.90m,
                            PublisherId = 1,
                            RentalPrice = 1.50m,
                            Title = "Book2",
                            UnitNumber = 3,
                            UnitsRented = 15,
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5525),
                            UpdatedBy = 1,
                            YearOfPublish = 1899
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5526),
                            CreatedBy = 1,
                            Description = "Description about the book3",
                            LanguageId = 1,
                            ListPrice = 1.70m,
                            PublisherId = 2,
                            RentalPrice = 2.20m,
                            Title = "Book3",
                            UnitNumber = 3,
                            UnitsRented = 2,
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5526),
                            UpdatedBy = 1,
                            YearOfPublish = 2005
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5528),
                            CreatedBy = 1,
                            Description = "Description about the book tesla",
                            LanguageId = 2,
                            ListPrice = 1.30m,
                            PublisherId = 3,
                            RentalPrice = 1.90m,
                            Title = "Tesla",
                            UnitNumber = 5,
                            UnitsRented = 0,
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5528),
                            UpdatedBy = 1,
                            YearOfPublish = 2018
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.BookRental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentedFromDate")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentedToDate")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnedDate")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Updated")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("BookRentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5562),
                            CreatedBy = 1,
                            OrderId = 1,
                            RentedFromDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentedToDate = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnedDate = new DateTime(2020, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Closed",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5562),
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5564),
                            CreatedBy = 1,
                            OrderId = 2,
                            RentedFromDate = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentedToDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnedDate = new DateTime(2020, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Closed",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5565),
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5574),
                            CreatedBy = 1,
                            OrderId = 3,
                            RentedFromDate = new DateTime(2020, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RentedToDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Opened",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5575),
                            UpdatedBy = 1
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Updated")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<int>("VAT")
                        .HasPrecision(4)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5603),
                            CreatedBy = 1,
                            Name = "England",
                            ShortName = "Eng",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5604),
                            UpdatedBy = 1,
                            VAT = 25
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5605),
                            CreatedBy = 1,
                            Name = "France",
                            ShortName = "Fra",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5605),
                            UpdatedBy = 1,
                            VAT = 20
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5607),
                            CreatedBy = 1,
                            Name = "Germany",
                            ShortName = "GER",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5607),
                            UpdatedBy = 1,
                            VAT = 10
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Updated")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5634),
                            CreatedBy = 1,
                            Description = "Description about the genre 1 ",
                            IsActive = true,
                            Name = "Genre 1",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5635),
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5636),
                            CreatedBy = 1,
                            Description = "Description about the genre 2",
                            IsActive = false,
                            Name = "Genre 2",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5637),
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5638),
                            CreatedBy = 1,
                            Description = "Description about the genre 3",
                            IsActive = true,
                            Name = "Genre 3",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5638),
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5639),
                            CreatedBy = 1,
                            Description = "Description about the genre 3",
                            IsActive = true,
                            Name = "Documentary",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5639),
                            UpdatedBy = 1
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Updated")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5961),
                            CreatedBy = 1,
                            Name = "English",
                            ShortName = "Eng",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5961),
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5963),
                            CreatedBy = 1,
                            Name = "France",
                            ShortName = "Fra",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5963),
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5964),
                            CreatedBy = 1,
                            Name = "German",
                            ShortName = "Ger",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(5965),
                            UpdatedBy = 1
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Date")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalRentalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRentalPriceWithVAT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "E",
                            Date = new DateTime(2020, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRentalPrice = 1.20m,
                            TotalRentalPriceWithVAT = 1.50m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Currency = "U",
                            Date = new DateTime(2020, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRentalPrice = 1.20m,
                            TotalRentalPriceWithVAT = 1.50m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Currency = "E",
                            Date = new DateTime(2020, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRentalPrice = 1.60m,
                            TotalRentalPriceWithVAT = 2m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Currency = "E",
                            Date = new DateTime(2021, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalRentalPrice = 1.60m,
                            TotalRentalPriceWithVAT = 2m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Updated")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(6466),
                            CreatedBy = 1,
                            Name = "Publisher 1",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(6467),
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(6468),
                            CreatedBy = 1,
                            Name = "Publisher 2",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(6468),
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(6470),
                            CreatedBy = 1,
                            Name = "Publisher 3",
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 92, DateTimeKind.Utc).AddTicks(6470),
                            UpdatedBy = 1
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DefaultCurrency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("ApplicationCore.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("Created")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordCrypted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasMaxLength(25)
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<int?>("UserBasketId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserBasketId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Adresa 1",
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 323, DateTimeKind.Utc).AddTicks(8447),
                            CreatedBy = 1,
                            DateOfBirth = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "username1@gmail.com",
                            FirstName = "Name 1",
                            IsActive = true,
                            LastName = "Surname 1",
                            PasswordCrypted = "$2a$11$dg1qANaDBDinrMDVG.17ferYZX2kb0Zg7Z5lEjF0SbkLfJ6QNrI6i",
                            Role = 0,
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 323, DateTimeKind.Utc).AddTicks(8449),
                            UpdatedBy = 1,
                            UserBasketId = 1,
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Adresa 2",
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 561, DateTimeKind.Utc).AddTicks(6145),
                            CreatedBy = 1,
                            DateOfBirth = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test@gmail.com",
                            FirstName = "Name 2",
                            IsActive = true,
                            LastName = "Surname 2",
                            PasswordCrypted = "$2a$11$shQRy4DsTY.wN8tH7thkdebaYQnieJE5aDgUqzd1nuwHmHLzn980W",
                            Role = 2,
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 561, DateTimeKind.Utc).AddTicks(6146),
                            UpdatedBy = 1,
                            UserBasketId = 2,
                            Username = "User2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Adresa 2",
                            Created = new DateTime(2022, 8, 6, 6, 35, 26, 820, DateTimeKind.Utc).AddTicks(1511),
                            CreatedBy = 1,
                            DateOfBirth = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test2@gmail.com",
                            FirstName = "Name 3",
                            IsActive = true,
                            LastName = "Surname 3",
                            PasswordCrypted = "$2a$11$VkX/JrpJL9cOoAsMu0Pp9ePs5Ie2h.d7qxYmOAf2i2Qx6M1U7rfDC",
                            Role = 2,
                            Updated = new DateTime(2022, 8, 6, 6, 35, 26, 820, DateTimeKind.Utc).AddTicks(1512),
                            UpdatedBy = 1,
                            UserBasketId = 3,
                            Username = "User3"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.UserBasket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Currency")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("TotalRentalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRentalPriceWithVAT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("UserBaskets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "EUR",
                            TotalRentalPrice = 1.20m,
                            TotalRentalPriceWithVAT = 1.50m
                        },
                        new
                        {
                            Id = 2,
                            Currency = "USD",
                            TotalRentalPrice = 1.0m,
                            TotalRentalPriceWithVAT = 1.25m
                        },
                        new
                        {
                            Id = 3,
                            Currency = "GBP",
                            TotalRentalPrice = 1.60m,
                            TotalRentalPriceWithVAT = 2.0m
                        });
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 1
                        },
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 3
                        },
                        new
                        {
                            AuthorsId = 10,
                            BooksId = 4
                        });
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("BookGenre");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            GenresId = 1
                        },
                        new
                        {
                            BooksId = 2,
                            GenresId = 1
                        },
                        new
                        {
                            BooksId = 2,
                            GenresId = 2
                        },
                        new
                        {
                            BooksId = 3,
                            GenresId = 3
                        },
                        new
                        {
                            BooksId = 4,
                            GenresId = 4
                        });
                });

            modelBuilder.Entity("BookOrder", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("BookOrder");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            OrdersId = 4
                        },
                        new
                        {
                            BooksId = 2,
                            OrdersId = 3
                        },
                        new
                        {
                            BooksId = 3,
                            OrdersId = 2
                        },
                        new
                        {
                            BooksId = 4,
                            OrdersId = 1
                        });
                });

            modelBuilder.Entity("BookUserBasket", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("UserBasketsId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "UserBasketsId");

                    b.HasIndex("UserBasketsId");

                    b.ToTable("BookUserBasket");

                    b.HasData(
                        new
                        {
                            BooksId = 1,
                            UserBasketsId = 1
                        },
                        new
                        {
                            BooksId = 2,
                            UserBasketsId = 1
                        },
                        new
                        {
                            BooksId = 3,
                            UserBasketsId = 2
                        },
                        new
                        {
                            BooksId = 4,
                            UserBasketsId = 3
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Author", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Book", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("ApplicationCore.Entities.BookRental", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Order", b =>
                {
                    b.HasOne("ApplicationCore.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationCore.Entities.SystemSettings", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ApplicationCore.Entities.User", b =>
                {
                    b.HasOne("ApplicationCore.Entities.UserBasket", "UserBasket")
                        .WithMany()
                        .HasForeignKey("UserBasketId");

                    b.Navigation("UserBasket");
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookOrder", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookUserBasket", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.UserBasket", null)
                        .WithMany()
                        .HasForeignKey("UserBasketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Entities.Language", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("ApplicationCore.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
